---

- hosts: docker-container
  name: My Web Server Deployment
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present

  - name: Deploy Custom Web Page
    copy: src=files/index.html dest=/var/www/html/index.html

  - name: Deploy Custom Web Page
    template: src=templates/info.j2 dest=/var/www/html/info.html
  
  - name: Start the Apache Service 
    command: "apache2ctl  start"
